# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        
    # entities:
        # Bio:
        #     form:
        #         fields:
        #             - { property: 'title', type: 'fos_ckeditor' }
        #             - { property: 'text', type: 'fos_ckeditor' }